### ISSUE TITLE
Is it possible to connect automatically at the email address without user logging in ?

### ISSUE THREAD

**Issue by pappleweb** [dacastro4/laravel-gmail#42]
Hi,

I want that the connection to GMAIL at the email address (example : ticketingsupport@gmail.com) to be automatic without the user having to login ?

This email address is a common address and we have more users of the application who reply at a mail.

In fact, I want to create a ticketing application connected at GMAIL. Your program help me to receive any messages in the lavaral application.

Is it possible ?

Thanks you :)

**Comment by dacastro4** [comment]
I have something similar to the app that you're building. I have a single account where I receive a bunch of emails that I process every 15 mins, with that said, I never found a way with the google keys/JSON files but what I did was create a "Settings" page where I logged in with that email and never change it again because the token refreshes itself.

**Comment by jaythegeek** [comment]
FYI as a simple workaround for this, I have wrapped up the "collection" of messages into a Job, inside the handle() part of the job I am passing the userId in and then spoofing LaravelGmail by using ````auth()->loginUsingId($this->userId);```` this works just fine for now however ideally unhooking LaravelGmail from the Auth system in some way would be a better resolution

**Comment by novakben** [comment]
hey @jaythegeek does this still work for you? did you find any caveats? I'm considering implementing the same approach.
